<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration [
        <!ELEMENT generatorConfiguration (classPathEntry|context)*>
        <!ELEMENT classPathEntry (#PCDATA)>
        <!ATTLIST classPathEntry
                location CDATA #REQUIRED>
        <!ELEMENT context (commentGenerator|jdbcConnection|javaTypeResolver|javaModelGenerator|sqlMapGenerator|javaClientGenerator|table)*>
        <!ATTLIST context
                id CDATA #REQUIRED
                targetRuntime CDATA #REQUIRED>
        <!ELEMENT commentGenerator (property)*>
        <!ELEMENT property (#PCDATA)>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        <!ELEMENT jdbcConnection (#PCDATA)>
        <!ATTLIST jdbcConnection
                driverClass CDATA #REQUIRED
                connectionURL CDATA #REQUIRED
                userId CDATA #REQUIRED
                password CDATA #REQUIRED>
        <!ELEMENT javaTypeResolver (property)*>
        <!ELEMENT javaModelGenerator (property)*>
        <!ATTLIST javaModelGenerator
                targetPackage CDATA #REQUIRED
                targetProject CDATA #REQUIRED>
        <!ELEMENT sqlMapGenerator (property)*>
        <!ATTLIST sqlMapGenerator
                targetPackage CDATA #REQUIRED
                targetProject CDATA #REQUIRED>
        <!ELEMENT javaClientGenerator (property)*>
        <!ATTLIST javaClientGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetProject CDATA #REQUIRED>
        <!ELEMENT table (#PCDATA)>
        <!ATTLIST table
                tableName CDATA #REQUIRED
                domainObjectName CDATA #REQUIRED
                enableCountByExample CDATA #REQUIRED
                enableUpdateByExample CDATA #REQUIRED
                enableDeleteByExample CDATA #REQUIRED
                enableSelectByExample CDATA #REQUIRED
                selectByExampleQueryId CDATA #REQUIRED>
        ]>
<generatorConfiguration>
    <!-- 数据库驱动:选择你的本地硬盘上面的数据库驱动包-->
    <classPathEntry  location="E:\developer\lib\mysql-connector-java-5.0.4-bin.jar"/>
    <context id="DB2Tables"  targetRuntime="MyBatis3">
        <commentGenerator>
            <property name="suppressDate" value="true"/>
            <!-- 是否去除自动生成的注释 true：是 ： false:否 -->
            <property name="suppressAllComments" value="true"/>
        </commentGenerator>
        <!--数据库链接URL，用户名、密码 -->
        <jdbcConnection driverClass="com.mysql.jdbc.Driver" connectionURL="jdbc:mysql://127.0.0.1/mytest" userId="root" password="123456">
        </jdbcConnection>
        <javaTypeResolver>
            <property name="forceBigDecimals" value="false"/>
        </javaTypeResolver>
        <!-- 生成模型的包名和位置-->
        <javaModelGenerator targetPackage="com.winter.model" targetProject="src/main/java">
            <property name="enableSubPackages" value="true"/>
            <property name="trimStrings" value="true"/>
        </javaModelGenerator>
        <!-- 生成映射文件的包名和位置-->
        <sqlMapGenerator targetPackage="mapping" targetProject="src/main/resources">
            <property name="enableSubPackages" value="true"/>
        </sqlMapGenerator>
        <!-- 生成DAO的包名和位置-->
        <javaClientGenerator type="XMLMAPPER" targetPackage="com.winter.dao" targetProject="src/main/java">
            <property name="enableSubPackages" value="true"/>
        </javaClientGenerator>
        <!-- 要生成的表 tableName是数据库中的表名或视图名 domainObjectName是实体类名-->
        <table tableName="t_user" domainObjectName="User" enableCountByExample="false" enableUpdateByExample="false" enableDeleteByExample="false" enableSelectByExample="false" selectByExampleQueryId="false"></table>
    </context>
</generatorConfiguration>
